<a href="https://colab.research.google.com/github/abdulmoiz99/TensorFlow/blob/main/TenserFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [2]:
iris = datasets.load_iris()

In [3]:
data = pd.DataFrame(data = np.c_[iris['data'], iris['target']],
                    columns = iris['feature_names'] + ['target'])

In [4]:
data

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2     0.0
1                  4.9               3.0  ...               0.2     0.0
2                  4.7               3.2  ...               0.2     0.0
3                  4.6               3.1  ...               0.2     0.0
4                  5.0               3.6  ...               0.2     0.0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3     2.0
146                6.3               2.5  ...               1.9     2.0
147                6.5               3.0  ...               2.0     2.0
148                6.2               3.4  ...               2.3     2.0
149                5.9               3.0  ...               1.8     2.0

[150 rows x 5 columns]

In [5]:
X = data.iloc[:,0:3].values
Y = data.iloc[:,4].values


In [6]:
Y
# 0 -> 1 0 0
# 1 -> 0 1 0
# 2 -> 0 0 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [7]:
Y = pd.get_dummies(Y).values

In [8]:
Y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [10]:
Y_test

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [11]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [12]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(32, activation='relu')) # // no of neurons
model.add(tf.keras.layers.Dense(3, activation='relu'))


model.compile(optimizer = 'adamax',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

history = model.fit(X_train,Y_train, validation_data = (X_test,Y_test), batch_size =50, epochs = 20)

Epoch 1/20
3/3 [==============================] - 1s 89ms/step - loss: 1.3315 - accuracy: 0.3667 - val_loss: 1.4494 - val_accuracy: 0.2000
Epoch 2/20
3/3 [==============================] - 0s 13ms/step - loss: 1.3034 - accuracy: 0.3667 - val_loss: 1.4087 - val_accuracy: 0.2000
Epoch 3/20
3/3 [==============================] - 0s 13ms/step - loss: 1.2816 - accuracy: 0.3667 - val_loss: 1.3773 - val_accuracy: 0.2000
Epoch 4/20
3/3 [==============================] - 0s 13ms/step - loss: 1.2672 - accuracy: 0.3667 - val_loss: 1.3523 - val_accuracy: 0.2000
Epoch 5/20
3/3 [==============================] - 0s 14ms/step - loss: 1.2531 - accuracy: 0.3583 - val_loss: 1.3339 - val_accuracy: 0.2000
Epoch 6/20
3/3 [==============================] - 0s 12ms/step - loss: 1.2431 - accuracy: 0.3500 - val_loss: 1.3180 - val_accuracy: 0.1333
Epoch 7/20
3/3 [==============================] - 0s 12ms/step - loss: 1.2339 - accuracy: 0.3250 - val_loss: 1.3046 - val_accuracy: 0.1333
Epoch 8/20
3/3 [===========

In [13]:
from matplotlib import pyplot
pyplot.title('Loss')  
pyplot.plot(history.history['loss'], label = 'train')
pyplot.plot(history.history['val_loss'],label = 'test')
pyplot.legend()
pyplot.show()

Model That Save the Best Accuracy

In [14]:
!pip install -pyyaml h5py
filepath = 'iris_best_model.hdf5'


Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -p


In [21]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [19]:
from keras.callbacks import ModelCheckpoint, EarlyStopping

In [22]:
create_model = True
model = tf.keras.models.Sequential()

if create_model:
  model.add(tf.keras.layers.Input(shape=(3)))
  model.add(tf.keras.layers.Dense(512, activation='relu')) # // no of neurons
  model.add(tf.keras.layers.Dropout(0.5))
  model.add(tf.keras.layers.Dense(16, activation='relu'))
  model.add(tf.keras.layers.Dropout(0.5))
  model.add(tf.keras.layers.Dense(3, activation='relu'))
else:
  model = load_model(filepath)

model.compile(loss = 'categorical_crossentropy',
              optimizer = 'adam',
              metrics = ['accuracy'])

es = EarlyStopping(monitor = 'val_loss',mode = 'min',verbose = 1, patience = 10)
mc = ModelCheckpoint(filepath = filepath, monitor = 'val_accuracy', mode = 'max', verbose = 1, save_best_only = True)

history = model.fit(X_train,Y_train, validation_data = (X_test,Y_test), batch_size =50, epochs = 20)



Epoch 1/20
3/3 [==============================] - 1s 80ms/step - loss: nan - accuracy: 0.2917 - val_loss: nan - val_accuracy: 0.3667
Epoch 2/20
3/3 [==============================] - 0s 13ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 3/20
3/3 [==============================] - 0s 14ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 4/20
3/3 [==============================] - 0s 14ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 5/20
3/3 [==============================] - 0s 15ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 6/20
3/3 [==============================] - 0s 13ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 7/20
3/3 [==============================] - 0s 14ms/step - loss: nan - accuracy: 0.3250 - val_loss: nan - val_accuracy: 0.3667
Epoch 8/20
3/3 [==============================] - 0s 15ms/step - loss